### PR TITLE
Added new snippets: elseif, include, assign(short)

### PR DESCRIPTION
**Pull request by vinlos**

### CODE REVIEW

**Comment by dcortes92** [comment]
Hey, thanks for submitting your PR. I'll be reviewing this shortly.

Cheers

**Comment by vinlos** [comment]
Thank you Daniel!
Cheers

**Comment by dcortes92** [comment]
Hey @vinlos congrats on your first PR 🎉. Your changes were merged and a new version for the extension is now available on the store.

Cheers

**Comment by vinlos** [comment]
Thank you Daniel. I don't exclude to add new contributions with other snippets and features
;)

See you,
Vincenzo

**Comment by vinlos** [comment]
Thank you Daniel. I don't exclude to add new snippets in the next future.

BTW I have not yet found a new version with my changes in the store.

May you please have a look, if you have time! Thank you in advance,
Vincenzo

Il giorno mer 2 nov 2016 alle ore 15:05 Daniel Cortes <
notifications@github.com> ha scritto:

Hey @vinlos <https://github.com/vinlos> congrats on your first PR 🎉. Your
changes were merged and a new version for the extension is now available on
the store.

Cheers

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/dcortes92/vs-freemarker/pull/3#issuecomment-257873936>,
or mute the thread

**Comment by dcortes92** [comment]
Hey @vinlos, sorry for the late reply. I'm pretty sure I published a new version once I merged your PR. Current version is `0.0.3` can you please tell me which version do you currently have?

--- Edit ---

Woops, turns out I published the extension with a different name 😓. I now fixed the issue, new version is `0.0.5`. Keep the contributions coming 💯. Let me know if you're able to update the extension. Thanks,

Daniel

**Comment by vinlos** [comment]
Hi Daniel,

my version is 0.0.3, but I'm still missing new snippets, like *elseif**, *while
they were working fine in the local version. In fact, if you look to your
local snippet.json it is different from the one coming from my pull request.

Cheers,
Vincenzo

Il giorno lun 30 gen 2017 alle ore 21:21 Daniel Cortes <
notifications@github.com> ha scritto:

**Comment by dcortes92** [comment]
Hi Vinlos,

Yesterday I unpublished a duplicate version of the extension. Perhaps you installed that one. What I recommend is to uninstall the extension and install it again. As you can see [here](https://marketplace.visualstudio.com/items?itemName=dcortes92.FreeMarker) current version is `0.0.5` which includes your snippets. I also created some issues [here](https://github.com/dcortes92/vs-freemarker/issues) with the pending work I'd like for future versions. If you can help me with any of those I will greatly appreciate it.

Thanks,

Daniel

**Comment by vinlos** [comment]
Hello Daniel,

after reinstalling the extension, I was able to get the new version. Thank
you very much!

I'll try to help you on the tasks you mentioned. Cheers,
Vincenzo

Il giorno mar 31 gen 2017 alle ore 16:14 Daniel Cortes <
notifications@github.com> ha scritto:

**Pull request merged**
